### ISSUE TITLE
Duty cycle resolution and printing to serial port

### ISSUE THREAD

**Issue by prabiei** [khoih-prog/SAMD_Slow_PWM#1]
I am trying to use slow PWI with a float duty cycle. Ideally I like to set duty cycles to several digits. For example if PWM frequency is 1kHz, I like to be able to set PWM duty cycle resolution to 8nsec which is a duty cycle resolution of 0.000008. However with the current software it is only possible to change at a resolution of 0.01. Can you modify the software to achieve this. Also, when duty cycle is change the program prints to serial terminal. How can I turn the printing off?

**Comment by khoih-prog** [comment]
> set PWM duty cycle resolution to 8nsec which is a duty cycle resolution of 0.000008

There is no way this library, or even hardware-based PWM, can achieve that kind of **absurd resolution of 8nsec**.
You have to know that SAMD hardware timer clock is around 48MHz, and this `slow PWM` library can provide the accuracy around uSec or mSec range.

> Also, when duty cycle is change the program prints to serial terminal. How can I turn the printing off?

Changing in the example to have

```
#define _PWM_LOGLEVEL_      0
```

https://github.com/khoih-prog/SAMD_Slow_PWM/blob/da5c3ce61ffb704f206e72b65e8fd071093617ff/examples/SAMD21/ISR_Modify_PWM/ISR_Modify_PWM.ino#L26
