### ISSUE TITLE
missing header

### ISSUE THREAD

**Issue by toniMephis** [khoih-prog/SAMD_Slow_PWM#2]
Arduino IDE version: 1.8.19 (Windows 1.8.57.0)
Arduino SAMD Core Version 1.8.12
ARDUINO_SAMD_MKRWIFI1010
OS: Windows10

Context:
I encountered an  error while compiling SAMD_Slow_PWM.
"
In file included from ...\Arduino\libraries\SAMD_Slow_PWM\src/SAMD_Slow_PWM.h:30:0,
...\Arduino\libraries\SAMD_Slow_PWM\src/SAMD_Slow_PWM.hpp:138:10: fatal error: TimerInterrupt_Generic_Debug.h: No such file or directory
 #include "TimerInterrupt_Generic_Debug.h"
compilation terminated.
"

**Comment by khoih-prog** [comment]
Hi @toniMephis 

Thanks for your interest in the library and spotting my mistake in using the wrong name for the file.

To fix now, please install the [**SAMD_TimerInterrupt** library](https://github.com/khoih-prog/SAMD_TimerInterrupt) from Arduino Library Manager

I'll release a new version to fix this issue shortly.

Regards,

**Comment by toniMephis** [comment]
Ì pulled TimerInterrupt_Generic_Debug.h from repository SAMD_TimerInterrupt. It compiles now. However I slightly worry about the warnings "using SAMD hardware timer" and "CHANGING_PWM_END_OF_CYCLE == true"

**Comment by khoih-prog** [comment]
Just informational warnings for debugging purpose. Don't care about them.

**Comment by toniMephis** [comment]
works perfectly. GREAT!

**Comment by toniMephis** [comment]
Can you put something into an example or the readme about how to stop the PWM cleanly? Am I guessing right with detachInterrupt ???

**Comment by khoih-prog** [comment]
Hi @toniMephis 

The new [**SAMD_Slow_PWM releases v1.2.2**](https://github.com/khoih-prog/SAMD_Slow_PWM/releases/tag/v1.2.2) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/SAMD_Slow_PWM#contributions-and-thanks)

Best Regards,

---

### Releases v1.2.2

1. Use correct `PWM_Generic_Debug.h` file. Check [**missing header** #2](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/2)
2. Display informational warning only when `_PWM_LOGLEVEL_` > 3
3. Update `Packages' Patches`
