### ISSUE TITLE
float precisison of DutyCycle only sometimes working

### ISSUE THREAD

**Issue by toniMephis** [khoih-prog/SAMD_Slow_PWM#3]
Arduino IDE version: 1.8.19 (Windows 1.8.57.0)
Arduino SAMD Core Version 1.8.12
ARDUINO_SAMD_MKRWIFI1010
OS: Windows10
sketch: example ISR_Modify_PWM
screenshot attached
![Clipboard02](https://user-images.githubusercontent.com/100749721/156493887-a85a009d-32fa-4cb5-9614-571ed5f05ca7.png)
d

**Comment by khoih-prog** [comment]
Hi @toniMephis 

Thanks again for this bug report.

Please change these 2 lines

https://github.com/khoih-prog/SAMD_Slow_PWM/blob/b0229b7784402957ead495644c8a0c4d13a1c50a/examples/SAMD21/ISR_Modify_PWM/ISR_Modify_PWM.ino#L147-L148

from 

```
double PWM_Freq;
uint32_t PWM_DutyCycle;
```

to 

```
float PWM_Freq;
float PWM_DutyCycle;
```

I forgot to change after modifying `dutycycle` from `uint32_t` to `float`

Will update in the `master` as well as in new release.

**Comment by khoih-prog** [comment]
Hi @toniMephis 

The new [**SAMD_Slow_PWM releases v1.2.3**](https://github.com/khoih-prog/SAMD_Slow_PWM/releases/tag/v1.2.3) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/SAMD_Slow_PWM#contributions-and-thanks)

Best Regards,

PS:

I wish to have every user as **investigative and thorough** as you to test and reveal so many bugs of this library.
I'm just afraid that there will be less and less of bugs for us to deal with in the future ;={}

---

### Releases v1.2.3

1. Fix `DutyCycle` bug. Check [float precisison of DutyCycle only sometimes working #3](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/3)
2. Fix `New Period` display bug. Check [random dropouts #4](https://github.com/khoih-prog/SAMD_Slow_PWM/issues/4)
3. Update examples
